basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API para gestionar categorías en una tienda virtual
  termsOfService: http://swagger.io/terms/
  title: Categories API
  version: "1.0"
paths: {}
swagger: "2.0"
